intrus = {
    "Les fleurs": [["Gerbera", "Cinéraire", "Edelweiss"], ["Jaunelle"]],
    "Films avec Tom Hanks": [["Sully", "La ligne rouge", "Da vinci code"], ["Seul au monde"]],
    "Fromages français": [["Beaufort", "Munster", "L'Etivaz"], ["L'époisses"]],
    "Villes italiennes": [["Bari", "Vérone", "Trieste"], ["Cordoue"]],
    "Chevaliers de la Table ronde": [["Bohort", "Victor", "Gauvain"], ["Tristan"]],
    "Monnaies du monde": [["Sanfri", "Roupie", "Couronne"], ["Peso"]],
    "Prix Nobel de la paix": [["Barack Obama", "Mahatma Gandhi", "Mikhaïl Gorbatchev"], ["Nelson Mandela"]],
    "Petits des animaux": [["Chamelon", "Gorillon", "Poney"], ["Levraut"]],
    "Os du corps humain": [["Fibrolite", "Tibia", "Patella"], ["Fibrolite"]],
    '"Merci" en langue étrangère': [["Arigatō", "Danke", "Gracie"], ["Prego"]],
    "Sports des Jeux Olympiques d'été": [["Ski Nautique", "Aviron", "Boxe"], ["Triathlon"]],
    "Films de Steven Spielberg": [["Ready player One", "Apollo 13", "The Fabelmans"], ["Amistad"]],
    "Déesses grecques": [["Héra", "Rhéa", "Déméter"], ["Hathor"]],
    "Mots bien orthographiés": [["Chrisalide", "Aberrance", "Ascendant"], ["Huit-clos"]],
    "États des États-Unis": [["Hawaï", "New York", "Georgie du Sud"], ["Nouveau-Mexique"]],
    "Vocabulaire des échecs": [["Roque", "Zeitnot", "Tunnel"], ["Gambit"]],
    "Anciens peuples": [["Wisigoths", "Pictes", "Parisii"], ["Hermanites"]],
    "Premiers ministres français": [["François Fillon", "Jacques Delors", "Michel Rocard"], ["Jacques Chirac"]],
    "Champignons": [["Clématite", "Girolle", "Coulemelle"], ["Pied-de-mouton"]],
    "Séries des années 80": [["Alf", "Superocpter", "Docteur Quinn"], ["K2000"]],
    "Montagnes": [["L'Aconcagua", "Le mont Anabalia", "Le mont Kosciuszko"], ["Le Denali"]],
    "Capitales d'Amérique du Sud": [["Santa Cruz", "Caracas", "Lima"], ["Santiago"]],
    "Compositeurs allemands": [["Richard Wagner", "Erik Satie", "Richard Strauss"], ["Ludwig von Beethoven"]],
    "Chansons de Michael Jackson": [["Bad", "Dirty Diana", "Smooth Criminal"], ["Love me again"]],
    "Films de Tim Burton": [["Beetlejuice", "Charlie et la chocolaterie"], ["La famille Addams", "Batman"]],
    "Fleuves d'Europe": [["Le fleuve rouge", "Le Pô", "L'Escaut"], ["Le Danube"]],
    "Mouvements artistiques": [["Le cubisme", "Le fauvisme", "Le fabulisme"], ["Le symbolisme"]],
    "Nombres premiers": [["41", "29", "23"], ["30"]],
    "Noms de villes françaises": [["Vatan", "Nigaud", "Bidon"], ["Simplé"]],
    "Vocabulaire de la poésie": [["Sonnet", "Litote", "Assonance"], ["Alexandrin"]],
}

infosAnnexes = {
    "Les fleurs": "Les fleurs sont souvent utilisées pour exprimer des émotions et des sentiments. Elles sont également un symbole de beauté et de nature.",
    "Films avec Tom Hanks": "Tom Hanks est un acteur américain connu pour ses rôles dans de nombreux films à succès, notamment 'Forrest Gump' et 'Saving Private Ryan'.",
    "Fromages français": "La France est célèbre pour sa grande variété de fromages, chacun ayant son propre goût et sa propre texture.",
    "Villes italiennes": "L'Italie est connue pour ses villes historiques, chacune ayant sa propre culture et son histoire.",
    "Chevaliers de la Table ronde": "Les chevaliers de la Table ronde sont des personnages légendaires du cycle arthurien, connus pour leurs aventures et leur quête du Saint Graal.",
    "Monnaies du monde": "Chaque pays a sa propre monnaie, qui peut varier en valeur par rapport aux autres monnaies.",
    "Prix Nobel de la paix": "Le Prix Nobel de la paix est décerné chaque année à des personnes ou des organisations qui ont fait des efforts significatifs pour promouvoir la paix dans le monde.",
    "Petits des animaux": "De nombreux animaux ont des noms spécifiques pour leurs jeunes, comme 'chiot' pour un jeune chien ou 'chaton' pour un jeune chat.",
    "Os du corps humain": "Le corps humain est composé de nombreux os, connaissez-vous les toutes?.",
    '"Merci" en langue étrangère': "Le mot 'merci' est utilisé dans de nombreuses langues pour exprimer la gratitude.",
    "Sports des Jeux Olympiques d'été": "Les Jeux Olympiques d'été sont un événement sportif international qui a lieu tous les quatre ans, mettant en vedette de nombreux sports différents.",
    "Films de Steven Spielberg": "Steven Spielberg est un réalisateur et producteur américain connu pour ses films emblématiques, notamment 'Jurassic Park' et 'E.T. l'extra-terrestre'.",
    "Déesses grecques": "Les déesses grecques sont des figures importantes de la mythologie grecque, chacune ayant ses propres attributs et histoires.",
    "Mots bien orthographiés": "L'orthographe correcte des mots est essentielle pour une communication claire et efficace.",
    "États des États-Unis": "Les États-Unis sont composés de 50 États, chacun ayant sa propre culture et son histoire.",
    "Vocabulaire des échecs": "Le vocabulaire des échecs comprend de nombreux termes techniques, chacun ayant une signification spécifique dans le contexte du jeu.",
    "Anciens peuples": "De nombreux peuples anciens ont laissé leur empreinte sur l'histoire, chacun ayant sa propre culture et ses propres traditions.",
    "Premiers ministres français": "Les premiers ministres français sont les chefs du gouvernement français, responsables de la mise en œuvre des politiques gouvernementales.",
    "Champignons": "Les champignons sont un groupe diversifié d'organismes, certains étant comestibles et d'autres toxiques.",
    "Séries des années 80": "Les séries des années 80 ont marqué une époque avec leurs intrigues captivantes et leurs personnages mémorables.",
    "Montagnes": "Les montagnes sont des formations géologiques qui se forment par le mouvement des plaques tectoniques.",
    "Capitales d'Amérique du Sud": "L'Amérique du Sud est composée de nombreux pays, chacun ayant sa propre capitale.",
    "Compositeurs allemands": "L'Allemagne a produit de nombreux compositeurs célèbres, chacun ayant contribué à la musique classique.",
    "Chansons de Michael Jackson": "Michael Jackson est souvent appelé le 'Roi de la Pop' et a eu une carrière musicale emblématique.",
    "Films de Tim Burton": "Tim Burton est un réalisateur connu pour son style visuel unique et ses histoires sombres et fantastiques.",
    "Fleuves d'Europe": "L'Europe est traversée par de nombreux fleuves, chacun ayant son propre écosystème et son importance géographique.",
    "Mouvements artistiques": "Les mouvements artistiques sont des périodes de temps où un certain style ou une certaine technique prédomine dans l'art.",
    "Nombres premiers": "Les nombres premiers sont des nombres naturels supérieurs à 1 qui n'ont pas d'autres diviseurs que 1 et eux-mêmes.",
    "Noms de villes françaises": "La France est connue pour ses nombreuses villes, chacune ayant sa propre culture et son histoire.",
    "Vocabulaire de la poésie": "La poésie utilise un langage figuré et des techniques littéraires pour exprimer des émotions et des idées.",
}