intrus = {
    "Les fleurs": [["Gerbera", "Cinéraire", "Edelweiss"], ["Jaunelle"]],
    "Films avec Tom Hanks": [["Sully", "La ligne rouge", "Da vinci code"], ["Seul au monde"]],
    "Fromages français": [["Beaufort", "Munster", "L'Etivaz"], ["L'époisses"]],
    "Villes italiennes": [["Bari", "Vérone", "Trieste"], ["Cordoue"]],
    "Chevaliers de la Table ronde": [["Bohort", "Victor", "Gauvain"], ["Tristan"]],
    "Monnaies du monde": [["Sanfri", "Roupie", "Couronne"], ["Peso"]],
    "Prix Nobel de la paix": [["Barack Obama", "Mahatma Gandhi", "Mikhaïl Gorbatchev"], ["Nelson Mandela"]],
    "Petits des animaux": [["Chamelon", "Gorillon", "Poney"], ["Levraut"]],
    "Os du corps humain": [["Fibrolite", "Tibia", "Patella"], ["Fibrolite"]],
    '"Merci" en langue étrangère': [["Arigatō", "Danke", "Gracie"], ["Prego"]],
    "Sports des Jeux Olympiques d'été": [["Ski Nautique", "Aviron", "Boxe"], ["Triathlon"]],
    "Films de Steven Spielberg": [["Ready player One", "Apollo 13", "The Fabelmans"], ["Amistad"]],
    "Déesses grecques": [["Hathor", "Rhéa", "Déméter"], ["Héra"]],
    "Mots bien orthographiés": [["Chrisalide", "Aberrance", "Ascendant"], ["Huit-clos"]],
    "États des États-Unis": [["Hawaï", "New York", "Georgie du Sud"], ["Nouveau-Mexique"]],
    "Vocabulaire des échecs": [["Roque", "Zeitnot", "Tunnel"], ["Gambit"]],
    "Anciens peuples": [["Wisigoths", "Pictes", "Parisii"], ["Hermanites"]],
    "Premiers ministres français": [["François Fillon", "Jacques Delors", "Michel Rocard"], ["Jacques Chirac"]],
    "Champignons": [["Clématite", "Girolle", "Coulemelle"], ["Pied-de-mouton"]],
    "Séries des années 80": [["Alf", "Superocpter", "Docteur Quinn"], ["K2000"]],
    "Montagnes": [["L'Aconcagua", "Le mont Anabalia", "Le mont Kosciuszko"], ["Le Denali"]],
    "Capitales d'Amérique du Sud": [["Santa Cruz", "Caracas", "Lima"], ["Santiago"]],
    "Compositeurs allemands": [["Richard Wagner", "Erik Satie", "Richard Strauss"], ["Ludwig von Beethoven"]],
    "Chansons de Michael Jackson": [["Bad", "Dirty Diana", "Smooth Criminal"], ["Love me again"]],
    "Films de Tim Burton": [["Beetlejuice", "Charlie et la chocolaterie"], ["La famille Addams", "Batman"]],
    "Fleuves d'Europe": [["Le fleuve rouge", "Le Pô", "L'Escaut"], ["Le Danube"]],
    "Mouvements artistiques": [["Le cubisme", "Le fauvisme", "Le fabulisme"], ["Le symbolisme"]],
    "Nombres premiers": [["2", "5", "13"], ["30"]],
    "Noms de villes françaises": [["Vatan", "Nigaud", "Bidon"], ["Simplé"]],
    "Vocabulaire de la poésie": [["Sonnet", "Litote", "Assonance"], ["Alexandrin"]],
}